spring:
  application:
    name: pokemon-service

server:
  port: 7002

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true