spring:
  application:
    name: eureka-service
  banner:
    location: "classpath:/banner/bannerDev.txt"

server:
  port: 8761

eureka:
  instance:
    hostname: localhost

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*,hystrix.stream"

application:
  version: 1.0
company:
  name: IZERTIS